### ISSUE TITLE
Dog Push not working

### ISSUE THREAD

**Issue by cagman** [trueaccord/DogPush#19]
Hi ,

I'm currently having issues running dogpush diff/push. Im able to download the config and init a new alerts file, however when I add the 'rule_files' file name reference to the config.yaml, i get the following errors:

Traceback (most recent call last):
  File "/usr/local/bin/dogpush", line 5, in <module>
    dogpush.main()
  File "/Library/Python/2.7/site-packages/dogpush/dogpush.py", line 422, in main
    args.command(args)
  File "/Library/Python/2.7/site-packages/dogpush/dogpush.py", line 316, in command_diff
    local_monitors = get_local_monitors()
  File "/Library/Python/2.7/site-packages/dogpush/dogpush.py", line 186, in get_local_monitors
    r = yaml.safe_load(f)
  File "/Library/Python/2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/Library/Python/2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "/Users/cgerasimou/dogpush/animus_monitors.yaml", line 15, column 25 

Can you please advise if i'm doing something wrong

**Comment by brownjohnf** [comment]
I'm experiencing something similar, and it appears to be a problem with dogpush outputting

```
options:
    escalation_message: !!python/unicode ''
```

into the monitors YAML. I'm not sure what caused this to start happening.

**Comment by cagman** [comment]
To add some further information, i was was running Dog Push off MacOS Sierra. As a work around, I was able to spin a Centos  instance on AWS and it worked without issue.

**Comment by cfstout** [comment]
FWIW I saw the same issues, looks to be a python to yaml serialization problem or something. Simply removing the `!!python/unicode ` part and just leaving the empty string worked for me.

**Comment by brownjohnf** [comment]
Yeah, removing the string works, until you pull down active monitors again and it adds that string back into the YAML.

**Comment by ewhauser** [comment]
I was able to fix this by changing:

https://github.com/trueaccord/DogPush/blob/e7e6a33e73d8bb7c5c1e47b5477ee561d6fb5ccd/dogpush/dogpush.py#L93

From `yaml.dump` to `yaml.safe_dump`

**Comment by cagman** [comment]
Confirmed that fix worked. Thanks @ewhauser

**Comment by bit-herder** [comment]
can we get this merged? this essentially makes this software unusable. did the dev abandon this?

**Comment by cfstout** [comment]
Last commit on this project was Oct 31, 2017. Looks to be dead. There's a more active fork https://github.com/dronedeploy/DogPush, I can try to PR my fix there..?

**Comment by ewhauser** [comment]
That's our fork. If you submit a PR, we will merge it.
